; PlatformIO Project Configuration
; ChromaCatch-Go ESP32-S3 BLE HID Mouse + WiFi HTTP Command Server

[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    https://github.com/wakwak-koba/ESP32-NimBLE-Mouse.git
    h2zero/NimBLE-Arduino@^2.1.0
    ArduinoJson@^7.0.0
